MeuGerenciador:
    LoginScreen:
    SupervisorScreen:
    VigilanteScreen:
    CadastroVigilanteScreen:
    RemoverVigilanteScreen:

<LoginScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    name: 'login_screen'
    FloatLayout:
        Image:
            source: 'grupoft.png'
            size_hint: 0.8, 0.8
            pos_hint: {"center_x": 0.5, "y": 0.40}
        TextInput:
            id: nome_usuario
            hint_text: 'USUÁRIO'
            multiline: False
            size_hint: 0.5, 0.06
            height: '50dp'
            font_size: '18sp'
            pos_hint: {'center_x': 0.5, 'y': 0.55}
        TextInput:
            id: senha_usuario
            hint_text: 'SENHA'
            password: True
            multiline: False
            size_hint: 0.5, 0.06
            height: '50dp'
            font_size: '18sp'
            pos_hint: {'center_x': 0.5, 'y': 0.45}
        Button:
            text: 'ENTRAR'
            size_hint: 0.3, None
            height: '50dp'
            font_size: '18sp'
            pos_hint: {'center_x': 0.5, 'y': 0.35}
            on_release: root.verificar_login()
        Button:
            text: 'FECHAR'
            size_hint: 0.15, None
            height: '50dp'
            font_size: '18sp'
            background_color: 1, 0, 0, 1
            pos_hint: {'center_x': 0.5, 'y': 0.25}
            on_release: app.fechar_aplicativo()

<SupervisorScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    name: "supervisor_screen"
    FloatLayout:
        Label:
            id: letreiro
            text: ''
            size_hint: None, None
            color: 0, 0, 0, 1
            pos_hint: {'center_x': 0.5, 'y': 0.55}
        Button:
            text: 'CADASTRAR VIGILANTE'
            size_hint: 0.3, None
            font_size: '18sp'
            height: '50dp'
            pos_hint: {'center_x': 0.5, 'y': 0.5}
            on_release: root.manager.current = 'cadastro_vigilante'
        Button:
            text: 'REMOVER VIGILANTE'
            size_hint: 0.3, None
            font_size: '18sp'
            height: '50dp'
            pos_hint: {'center_x': 0.5, 'y': 0.4}
            on_release: root.manager.current = 'remover_vigilante'
        Button:
            text: 'SAIR'
            size_hint: 0.15, None
            font_size: '18sp'
            height: '50dp'
            background_color: 1, 0, 0, 1
            pos_hint: {'center_x': 0.5, 'y': 0.3}
            on_release: root.manager.current = 'login_screen'

<CadastroVigilanteScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    name: 'cadastro_vigilante'
    Label:
        id: letreiro_cadastro_vigilante
        text: 'CADASTRO DE VIGILANTE'
        color: 0, 0, 0, 1
        size_hint_x: None
        size_hint_y: None
        pos_hint: {'x': 0.4, 'y': 0.84}
    TextInput:
        id: nome_completo
        hint_text: 'NOME COMPLETO'
        multiline: False
        size_hint_x: None
        size_hint_y: None
        width: 300
        height: '30dp'
        pos_hint: {'x': 0.3, 'y': 0.8}
    TextInput:
        id: login_vigilante
        hint_text: 'USUÁRIO'
        multiline: False
        size_hint_x: None
        size_hint_y: None
        width: 300
        height: '30dp'
        pos_hint: {'x': 0.3, 'y': 0.7}
    TextInput:
        id: senha1_vigilante
        hint_text: 'DIGITE UMA SENHA'
        password: True
        multiline: False
        size_hint_x: None
        size_hint_y: None
        width: 300
        height: '30dp'
        pos_hint: {'x': 0.3, 'y': 0.6}
    TextInput:
        id: senha2_vigilante
        hint_text: 'REPITA A SENHA'
        password: True
        multiline: False
        size_hint_x: None
        size_hint_y: None
        width: 300
        height: '30dp'
        pos_hint: {'x': 0.3, 'y': 0.5}
    Button:
        text: 'CADASTRAR VIGILANTE'
        width: self.texture_size[0] + 20
        height: '40dp'
        size_hint_x: None
        size_hint_y: None
        pos_hint: {'x': 0.36, 'y': 0.4}
        on_release: root.cadastrar_vigilante()
    Button:
        text: 'VOLTAR'
        background_color: 1, 0, 0, 1
        height: '40dp'
        size_hint_x: None
        size_hint_y: None
        pos_hint: {'x': 0.41, 'y': 0.3}
        on_release: root.manager.current = 'supervisor_screen'
    Label:
        id: letreiro_feed_back
        text: ''
        color: 1, 1, 1, 1
        size_hint_x: None
        size_hint_y: None
        pos_hint: {'x': 0.4, 'y': 0.25}

<RemoverVigilanteScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    name: 'remover_vigilante'
    Label:
        text: 'REMOVER CADASTRO'
        color: 0, 0, 0, 1
        size_hint_x: None
        size_hint_y: None
        pos_hint: {'x': 0.4, 'y': 0.65}
    TextInput:
        id: nome_vigilante_remover
        hint_text: 'NOME COMPLETO'
        multiline: False
        size_hint_x: None
        size_hint_y: None
        width: 300
        height: '30dp'
        pos_hint: {'x': 0.3, 'y': 0.6}
    Button:
        text: 'REMOVER CADASTRO'
        width: self.texture_size[0] + 20
        height: '40dp'
        size_hint_x: None
        size_hint_y: None
        pos_hint: {'x': 0.36, 'y': 0.5}
        on_release: root.remover_vigilante()
    Button:
        text: 'VOLTAR'
        background_color: 1, 0, 0, 1
        height: '40dp'
        size_hint_x: None
        size_hint_y: None
        pos_hint: {'x': 0.40, 'y': 0.4}
        on_release: root.manager.current = 'supervisor_screen'

<VigilanteScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    name: "vigilante_screen"
    GridLayout:
        cols: 1
        Label:
            id: letreiro_vigilante
            text: ''
            color: 0, 0, 0, 1
        Button:
            text: "Sair"
            background_color: 1, 0, 0, 1
            on_release: app.root.current = "login_screen"